package main

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/labstack/echo/v4"
	"github.com/mkobaly/jiraworklog"
)

// Verifies the embedded static assets are served without any filesystem
// dependency (binary must work regardless of working directory).
func TestEmbeddedStaticAssetsServed(t *testing.T) {
	e := echo.New()
	e.StaticFS("/static", echo.MustSubFS(jiraworklog.StaticFS, "static"))

	req := httptest.NewRequest(http.MethodGet, "/static/css/app.css", nil)
	rec := httptest.NewRecorder()
	e.ServeHTTP(rec, req)

	if rec.Code != http.StatusOK {
		t.Fatalf("GET /static/css/app.css: got status %d, want %d", rec.Code, http.StatusOK)
	}
	if body := rec.Body.String(); !strings.Contains(body, "turbo-progress-bar") {
		t.Errorf("response body does not look like app.css (missing expected selector)")
	}

	// tailwind.css is generated by build.sh (not committed); if this fails,
	// run ./build.sh to compile it before testing.
	req = httptest.NewRequest(http.MethodGet, "/static/css/tailwind.css", nil)
	rec = httptest.NewRecorder()
	e.ServeHTTP(rec, req)

	if rec.Code != http.StatusOK {
		t.Fatalf("GET /static/css/tailwind.css: got status %d, want %d (run ./build.sh to generate it)", rec.Code, http.StatusOK)
	}
	if body := rec.Body.String(); !strings.Contains(body, ".text-blue-600") {
		t.Errorf("response body does not look like compiled tailwind.css (missing expected utility class)")
	}
}
